#! /usr/bin/python

class Instance:
    def __init__(self):
        import sys
        self.__dict__.update((key, value) for key, value in sys._getframe(1).f_locals.items() if callable(value))
    def __len__(self):
        return self.__dict__['__len__']()


def Stack():
    stack = []
    def push(item):
        stack.append(item)
    def pop():
        return stack.pop()
    def __len__():
        return len(stack)
    return Instance()

if __name__ == '__main__':
    s = Stack()
    print(s)
    s.push(10)
    s.push(20)
    s.push('Hello')
    print(len(s))
    print(s.pop())
    print(s.pop())
    print(s.pop())
