#! /usr/bin/python

prices = {
   'ACME': 45.23,
   'AAPL': 612.78,
   'IBM': 205.55,
   'HPQ': 37.20,
   'FB': 10.75
}

print {x:y for x,y in prices.items() if y > 200}
print dict((x,y) for x,y in prices.items() if y > 200)

tech_names = { 'AAPL', 'IBM', 'HPQ', 'MSFT' }
print {x:y for x,y in prices.items() if x in tech_names}
