#! /usr/bin/python
from pprint import pprint

prices = {
   'ACME': 45.23,
   'AAPL': 612.78,
   'IBM': 205.55,
   'HPQ': 37.20,
   'FB': 10.75
}

p1 = { key:value for key, value in prices.items() if value > 200 }    # after in must be a list. the prices.item() return a list
pprint(p1)  #there have some different with print. e.g. the order of dict elements(from little to big).


tech_names = { 'AAPL', 'IBM', 'HPQ', 'MSFT' }
p2 = {key:value for key, value in prices.items() if key in tech_names}
pprint (p2)
