#! /usr/bin/python
# example.py
#
# Find out what two dictionaries have in common

a = {
   'x' : 1,
   'y' : 2,
   'z' : 3
}

b = {
   'w' : 10,
   'x' : 11,
   'y' : 2
}

print( "common keys in a and b : ", a.keys() & b.keys())    # Notice the ","
print( "keys in a not in b : ", a.keys() - b.keys())
print( "items in a and b : ", a.items() & b.items())
