#! /usr/bin/python
rows = [
    {'address': '5412 N CLARK', 'date': '07/01/2012'},
    {'address': '5148 N CLARK', 'date': '07/04/2012'},
    {'address': '5800 E 58TH', 'date': '07/02/2012'},
    {'address': '2122 N CLARK', 'date': '07/03/2012'},
    {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'},
    {'address': '1060 W ADDISON', 'date': '07/02/2012'},
    {'address': '4801 N BROADWAY', 'date': '07/01/2012'},
    {'address': '1039 W GRANVILLE', 'date': '07/04/2012'},
]

rows.sort(key=lambda s: s["date"])

from itertools import groupby

groups = groupby(rows, key=lambda s: s['date'])

for key, group in groups:
    print key
    for item in group:
        print "    ", item


from collections import defaultdict
groups = defaultdict(list)
for item in rows:
    date = item["date"]
    groups[date].append(item)

for x,group in groups.items():
    print x
    for g in group:
        print "    ", g

