#! /usr/bin/python

import heapq

def sort_key(d):
    return d['price']
    

portfolio = [
   {'name': 'IBM', 'shares': 100, 'price': 91.1},
   {'name': 'AAPL', 'shares': 50, 'price': 543.22},
   {'name': 'FB', 'shares': 200, 'price': 21.09},
   {'name': 'HPQ', 'shares': 35, 'price': 31.75},
   {'name': 'YHOO', 'shares': 45, 'price': 16.35},
   {'name': 'ACME', 'shares': 75, 'price': 115.65}
]

#heapq.nsmallest(3, portfolio, key=lambda d : d['price'])
nsmallest = heapq.nsmallest(3, portfolio, key = sort_key)
print(nsmallest)

nlargest = heapq.nlargest(3, portfolio, key = sort_key)
print(nlargest)

