#! /usr/bin/python

#a = [1, 5, 2, 1, 9, 1, 5, 10]
a = [
    {'x': 2, 'y': 3},
    {'x': 1, 'y': 4},
    {'x': 2, 'y': 3},
    {'x': 2, 'y': 3},
    {'x': 10, 'y': 15}
]


def queue(items, key):
    d = set()
    for item in items:
        elmt = item if key is None else key(item)
        if elmt not in d:
            yield elmt
            d.add(elmt)

print a
print list(queue(a, key=lambda s: (s['x'], s['y'])))
