#! /usr/bin/python
# example.py
#
# Example of a priority queue

import heapq

class Item(object):
    def __init__(self, data):
        self.data = data

    # 很重要哟
    def __repr__(self):
        return self.data


class Priqueue(object):
    def __init__(self):
        self.heap = []
        self.idx = 0

    def push(self, item, priority):
        self.idx += 1
        heapq.heappush(self.heap, (-priority, self.idx, item))

    def pop(self):
        #_, _, item = heapq.heappop(self.heap)
        #return item
        return heapq.heappop(self.heap)[-1]

myqueue = Priqueue()
myqueue.push(Item("aaaa"), 5)
myqueue.push(Item("xxxx"), 1)
myqueue.push(Item("bbbb"), 4)
myqueue.push(Item("yyyy"), 1)


print("should be aaaa : ", myqueue.pop())
print("should be bbbb : ", myqueue.pop())
print("should be xxxx : ", myqueue.pop())
print("should be yyyy : ", myqueue.pop())

