#! /usr/bin/python

import os

filenames = os.listdir(os.path.expanduser('~'))
for name in filenames:
    if '.py' in name:   #if a file is .pyabc ?
        print ('There is a python file')
        find = 1
if not find:
    print('Sorry, no python.')

if any(name.endswith('.py') for name in filenames):
    print ('There is a python file')
else:
    print('Sorry, no python.')


l = ["ACME", 50, 123.45]

string = ", ".join(str(s) for s in l)
print(string)

portfolio = [
   {'name':'GOOG', 'shares': 50},
   {'name':'YHOO', 'shares': 75},
   {'name':'AOL', 'shares': 20},
   {'name':'SCOX', 'shares': 65}
]


from operator import itemgetter
item = min(portfolio, key=itemgetter('shares'))
print(item)
