GPP=g++ -g

all:
	$(GPP) math_test.cpp -std=c++0x -o math_test
	$(GPP) sizeof_test.cpp -std=c++0x -o sizeof_test
	$(GPP) cast_test.cpp -std=c++0x -o cast_test
	$(GPP) case_test.cpp -std=c++0x -o case_test
	$(GPP) exception_test.cpp -std=c++0x -o exception_test

clean:
	rm -f math_test
	rm -f sizeof_test
	rm -f cast_test
	rm -f case_test
	rm -f exception_test
