#! /usr/bin/python

from collections import deque

def search(f, pattern, length) :
    pre_lines = deque(maxlen=length)
    for line in f.readlines() :
        if pattern in line :
           yield line, pre_lines 
        pre_lines.append(line)

if __name__ == '__main__':
    with open('somefile.txt') as f:
        for line, pre_lines in search(f, 'python', 5):
            for x in pre_lines:
                print(x, end="")
            print(line, end="")
            print('-' * 20)
