GPP=g++ -g

all:
	g++ test1.cpp -o test1
	g++ test2.cpp -o test2
	g++ test3.cpp -std=c++0x -o test3
	g++ test4.cpp -std=c++0x -o test4
	g++ overload1.cpp -std=c++0x -o overload1
	g++ overload2.cpp -std=c++0x -o overload2

clean:
	rm -f test1
	rm -f test2
	rm -f test3
	rm -f test4
	rm -f overload1
	rm -f overload2
