GPP=g++ -g

all:
	$(GPP) string_test.cpp -std=c++0x -o string_test
	$(GPP) foreach_test.cpp -std=c++0x -o foreach_test
	$(GPP) vector_test.cpp -std=c++0x -o vector_test
	$(GPP) iter_test.cpp -std=c++0x -o iter_test
	$(GPP) array_test.cpp -std=c++0x -o array_test

clean:
	rm -f string_test
	rm -f foreach_test
	rm -f vector_test
	rm -f iter_test
	rm -f array_test
