#! /usr/bin/python

prices = {
   'ACME': 45.23,
   'BBBB': 45.23,
   'AAAA': 45.23,
   'AAPL': 612.78,
   'IBM': 205.55,
   'HPQ': 37.20,
   'FB': 10.75
}


print min(prices.items(), key=lambda p: p[1])
print min(zip(prices.values(), prices.keys()))

print max(prices.items(), key=lambda p: p[1])
print max(zip(prices.values(), prices.keys()))

print sorted(prices.items(), key=lambda p: p[1])
