#! /usr/bin/python

import re

# Some sample text
text = 'Today is 11/27/2012. PyCon starts 3/13/2013.'

#re.compile and re.fildall
dp = re.compile(r'\d+/\d+/\d+')
ret = re.findall(dp, text)
print(ret)

#re.compile and re.findall
dp = re.compile(r'(\d+)/(\d+)/(\d+)')
for month, day, year in re.findall(dp, text):
    print('{}-{}-{}'.format(month, day, year))

#re.compile, dp.finditer() and re.groups
for m in dp.finditer(text):      #object dp call it.
    print(m.groups())   # ('11', '27', '2012')
    print(m.group())    # 11/27/2012
