#! /usr/bin/python

from collections import namedtuple

stock = namedtuple('Stock', ['name', 'shares', 'price'])

# Some Data
records = [
    ('GOOG', 100, 490.1),
    ('ACME', 100, 123.45),
    ('IBM', 50, 91.15)
]

def compute_cost(records):
    total = 0.0
    for elm in records:
        s = stock(*elm)     # 注意*号的使用方法
        total += s.shares * s.price
    return total

print(compute_cost(records))
